nevents=10000
dologpt=1
dosvm=1
doslowsvm=1
dostandardization=0
ntrkmin = 0
ntrkmax = 40
ntrkbins = 20
ptbinningfactor = 10
lambdaarray=[0.1, 0.5, 1, 2, 3]
#lambdaarray=[10]
npzfiledirectory = "/gpfs/slac/atlas/fs1/d/woodsn/myscripts/training_minions/sept10_npzfiles/"
bkgnpzfilelocation = npzfiledirectory + "bkg.npz"
outputdir = "output"
